### ISSUE TITLE
`attr` vs `attrs`

### ISSUE THREAD

**Issue by dougthor42** [DanielSank/constraintula#15]
This project has a dependency on `attr` (https://github.com/DanielSank/constraintula/blob/master/setup.py#L40) but it looks like it's actually using the `attrs` library and API (https://github.com/DanielSank/constraintula/blob/master/constraintula_test.py#L45).

I think the dependency on `attr` is superfluous. The dev dependency `pytest` ends up installing `attrs` which shadows the `attr` module. Any issues with removing `attr`?

**Comment by maffoo** [comment]
The python package we want is `attrs`, so we should indeed remove `attr` from the requirements. But note that the `attrs` package (https://pypi.org/project/attrs/) provides a python package called `attr` so `import attr` is fine in code. However, this is the "old" way of doing things; the more [modern way](https://www.attrs.org/en/stable/names.html) is indeed to use `import attrs` which should clean up a lot confusion :-)
