### ISSUE TITLE
int attribute created as float in dataclass

### ISSUE THREAD

**Issue by mgiustina** [DanielSank/constraintula#7]
I build a constrained dataclass as follows:
```python

width, n_posts, pitch, corner_post_separation = constraintula.symbols(
        'width n_posts pitch corner_post_separation')

@constraintula.constrain(
        [width - ((n_posts - 1) * pitch + (2 * corner_post_separation))])
@attr.dataclass(frozen=True)
class EdgeAllocation:
    width: float
    n_posts: int
    pitch: float
    corner_post_separation: float
```
I can then build
```
edge_from_pitch = EdgeAllocation(total_width=6000, n_posts=12, pitch=460)
```
which creates a fully constrained `EdgeAllocation` class:
```
<< edge_from_pitch

>> EdgeAllocation(total_width=6000.00000000000, n_posts=12.0000000000000, pitch=460.000000000000, corner_post_separation=470.000000000000)
```
However, the type of `n_posts` should be an int according to the dataclass constructor. Instead I get
```
<< type(edge_from_pitch.n_posts)

>> sympy.core.numbers.Float
```
This should not be a valid `EdgeAllocation` class.

**Comment by DanielSank** [comment]
Thank you for posing this. I believe this problem is fixable by adding support for input/output conversion functions with defaults inferred from dataclass types when available. I'm interested in this because I think it will help support labrad units as well, so I'll take a look and then post a basic plan.

**Comment by mgiustina** [comment]
I'm actually curious what the intended functionality _should_ be here. For example, what if I set the constraints such that the right answer for an int-typed attribute actually is not an integer. I did that [here](https://github.com/qh-lab/pyle/pull/16690/files#diff-d928b3c4f0c61190ffffb597cd6ae333R372-R379): using constraintula once to get the "target" value of `n_posts` and then using it a second time to set the other parameters according to a reasonable int-type choice. But essentially I took advantage of this bug... I'm not sure what the "right answer" is.

**Comment by DanielSank** [comment]
Intended behavior:

* User optionally specifies a conversion function for each field in the class. These functions are applied after the mathematics are solved and before the data are stored. For example, a conversion function could be `int` or `lambda x: x * ns`.
* Providing these functions means that we give up the guarantee, normally provided by constriantula, that the values of the fields satisfy the constraint equations.

?

**Comment by joelburget** [comment]
I'm interested in this as well. In a component I worked on I had to include a conversion from `sympy.core.numbers.Float` to `float`, which I would like to get rid of. It seems there are two separate issues:

1. Constraining `int`s to be integer-valued. As far as I can see, constraintula has no notion of type, meaning it considers everything a float -- is that right? Could we use type annotations to know when to constrain `int`s to be integer valued? This would be like adding a constraint `x = floor(x)`.

2. Converting to Python-native types. Could we just coerce all return values? `sympy.core.numbers.Float` with `float` and `sympy.core.numbers.Integer` with `int`?

**Comment by DanielSank** [comment]
> Constraining `int`s to be integer-valued. As far as I can see, constraintula has no notion of type, meaning it considers everything a float -- is that right?

Yeah, presently constraintula has no notion of type; it even ignores dataclass type annotations.

> Could we use type annotations to know when to constrain `int`s to be integer valued?

Almost surely. The one hesitation I have about adding a default implementation of that is that it's not clear whether to round up or down, or what tolerances should be allowed. For example, if constraintula finds `x=1.4` is it really ok to make that an integer?

> This would be like adding a constraint x = floor(x).

Yeah I'm  more comfortable with something like that where the code is explicit about how things are being converted. But even there, we might want some kind of tolerance specification so we can raise an error if we're converting 1.5 to 1, which seems highly questionable in many cases.

> Converting to Python-native types. Could we just coerce all return values? `sympy.core.numbers.Float` with float and `sympy.core.numbers.Integer` with int?

Yeah that seems straightforward and reasonable.
